/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Airplane(props) {
  const { nodes, materials } = useGLTF('/model/airplane.glb')
  const helixref = useRef()

const Helix_Speed = 6

  useFrame((_state,delta)=>{
helixref.current.rotation.x += delta * Helix_Speed
  }) 
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PUSHILIN_Plane_Circle000.geometry}
        material={materials.plane}
      />
      <mesh
      ref={helixref}
        castShadow
        receiveShadow
        geometry={nodes.PUSHILIN_Plane_Helix.geometry}
        material={materials.plane}
        position={[1.09, 0.23, 0]}
      />
    </group>
  )
}

useGLTF.preload('/model/airplane.glb')
